version: '3.8'

services:
  products_service:
    build: ./products_service
    ports:
      - "8001:8000"
    networks:
      - app_network

  orders_service:
    build: ./orders_service
    ports:
      - "8002:8000"
    networks:
      - app_network

  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - products_service
      - orders_service
    networks:
      - app_network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - app_network

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - api_gateway
    networks:
      - app_network

networks:
  app_network:
    driver: bridge