global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "products_service"
    static_configs:
      - targets: ["products_service:8000"]

  - job_name: "orders_service"
    static_configs:
      - targets: ["orders_service:8000"]